### PR TITLE
Fix repo name in /git

### LINKED ISSUE #161: /git embed title has typo
Should be `arisa3`, not `arisa2`

### PR DESCRIPTION
**Pull request by fiffu**
Fixes #161

### CODE REVIEW

File: lib/functional/functional_test.go [hunk 1]
```diff
@@ -89,34 +90,28 @@ func Test_Zip_MixedTypes(t *testing.T) {
...
-		}
-
-		return false
+		copy(buf, original)
+		shuffled := Shuffle(buf)
+		return slices.Equal(original, shuffled)
 	}
 
-	for i := 0; i < trials; i++ {
+	testCount := 1000
```
Comment (fiffu) [inline lib/functional/functional_test.go:106]: Fixes https://github.com/fiffu/arisa3/actions/runs/12154307333/job/33893860455#step:5:29
